---
provisioner:
  name: chef_zero
  require_chef_omnibus: 12.3.0
  chef_omnibus_install_options: -d /tmp/vagrant-cache/vagrant_omnibus
  client_rb:
    audit_mode: :enabled

platforms:
  - name: vagrant-centos-6.6
    driver_plugin: vagrant
    driver_config:
      box: opscode-centos-6.6
      network:
        - ["forwarded_port", {guest: 80, host: 8080, auto_correct: true}]
        - ["forwarded_port", {guest: 443, host: 8443, auto_correct: true}]
      customize:
        cpus: 2
        memory: 4096

suites:
  - name: marketplace_ami
    run_list: test::default
    attributes:
      test:
        ssh_keyname: marketplace_builder
        ssh_keypath: <%= ENV['MARKETPLACE_BUILDER_SSH_KEY_PATH'] %>
        ssh_username: ec2-user
        audit: true
        security: true
        chef_server_url: http://127.0.0.1:8889
